### ISSUE TITLE
不能跳转

### ISSUE THREAD

**Issue by Zsfzy** [seolhw/alias-skip#1]
在工作目录配置了settings.json 但是没办法跳转

**Comment by Zsfzy** [comment]
{
    "alias-skip.mappings": {
        "@src":"/src"
    }
}

**Comment by seolhw** [comment]
之前确实有这个bug，现在已经修复了

**Comment by seolhw** [comment]
之前确实有这个bug，现在已经修复了

**Comment by seolhw** [comment]
感谢使用我的插件
