### ISSUE TITLE
@utils无法跳转

### ISSUE THREAD

**Issue by CodeChangingMe** [seolhw/alias-skip#5]
![image](https://user-images.githubusercontent.com/15611059/83371726-df7c4600-a3f5-11ea-9a88-7d693db9d228.png)
第二行的@components/echarts能识别出来，但是@utils/common识别不出来...~不知道为啥，我手动配置alias-skip.mappings，也还是不行~

**Comment by noyidoit** [comment]
same issue

**Comment by noyidoit** [comment]
加了jsconfig.json之后好了，参见[VSCode Intellisense does not work with webpack + alias](https://stackoverflow.com/questions/47181037/vscode-intellisense-does-not-work-with-webpack-alias/47186185#47186185)
