### ISSUE TITLE
scss文件@import跳转问题

### ISSUE THREAD

**Issue by yoruponder** [seolhw/alias-skip#7]
![image](https://user-images.githubusercontent.com/9858714/91375542-95b4c780-e84d-11ea-9e66-eeeea1b99c15.png)
老哥，scss文件里的@import能扩展跳转功能吗

**Comment by seolhw** [comment]
我这边测试scss是可以跳的，只要能被识别成路径，都是可以跳转的

**Comment by seolhw** [comment]
这个issues我先关闭了，还有问题的话，欢迎加我微信 13832246076

**Comment by seolhw** [comment]
这个确实是问题，最新版本0.0.25 已修复
